version: "3.8"

services:
  ai-router:
    build: ./app
    ports: 
      - 8000:80 #localhost port : container exposed port
    working_dir: /app/
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 80

  celery-worker:
    build: ./app
    restart: always
    command: celery -A worker.celery worker -l info -E
    depends_on:
      - ai-router

  dashboard:
    build: ./app
    ports:
      - 5555:5555
    command: celery -A worker.celery flower -l info
    depends_on:
      - ai-router
      - celery-worker
